### ISSUE TITLE
Nonexistent finetuning script

### ISSUE THREAD

**Issue by davda54** [nyu-mll/msgs#3]
Hi, thank you for releasing the code and data! I wanted to run finetuning on MSGS according to the instructions, but there is no `inductive_bias` branch in your [transformers fork](https://github.com/nyu-mll/transformers). Where can I find the `run_msgs.py` script? Thanks! :)

**Comment by alexwarstadt** [comment]
Thanks for letting us know! This was a mistake in the README: The name of the branch should be `msgs`. You can find the script here: https://github.com/nyu-mll/transformers/blob/msgs/examples/run_msgs.py
